### ISSUE TITLE
pageloader conflicts with build_runner

### ISSUE THREAD

**Issue by ValeriusGC** [google/pageloader#184]
Hi!
When i try to use angulardart projects like [here](https://angulardart.dev/tutorial/toh-pt1), all goes well until `pageloader` was adding.

Say, this works well:
```
dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.5.0
  build_test: ^0.10.7
  build_web_compilers: ^2.1.0
  test: ^1.6.3
```
but this
```
dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.5.0
  build_test: ^0.10.7
  build_web_compilers: ^2.1.0
  pageloader: ^3.0.0
  test: ^1.6.3
```
generates error:
```
Because build_runner >=1.3.4 depends on build_config >=0.4.0 <0.4.1 and pageloader >=3.0.0 depends on build_config ^0.3.1, build_runner >=1.3.4 is incompatible with pageloader >=3.0.0.
So, because angular_tour_of_heroes depends on both pageloader ^3.0.0 and build_runner ^1.5.0, version solving failed.
```
As one sees the problem is in build_config cross clashing, and no focuses with changing versions are working.

OS: Ubuntu 18.04
